services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    restart: always
    secrets:
      - db_password
      - db_root_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - inception_network


  wordpress:
    build: ./requirements/wordpress
    # container_name: wordpress
    networks:
      - inception_network
    restart: always
    depends_on:
      - mariadb
    secrets:
      - db_password
      - credentials
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - wordpress-data:/var/www/html


  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: inception_nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    entrypoint: ["/bin/sh", "-c", "/wait-for-wordpress.sh wordpress 9000 && nginx -g 'daemon off;'"]
    volumes:
      - wordpress-data:/var/www/html
      - ./requirements/nginx/wait-for-wordpress.sh:/wait-for-wordpress.sh
    networks:
      - inception_network

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt

volumes:
  mariadb-data:
  wordpress-data:

networks:
  inception_network:
    driver: bridge
