services:

  mariadb:
    image: mariadb:10.5
    restart: always
    secrets:
      - db_password
      - db_root_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - ./requirements/mariadb/conf/init.sh:/docker-entrypoint-initdb.d/init.sh
      - mariadb-data:/var/lib/mysql
      - ./requirements/mariadb/conf/my.cnf:/etc/mysql/mariadb.conf.d/99-custom.cnf:ro
    networks:
      - inception_network

  wordpress:
    build: ./requirements/wordpress
    restart: always
    depends_on:
      - mariadb
    secrets:
      - db_password
      - credentials
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - wordpress-data:/var/www/html
      - ./requirements/wordpress/conf:/docker-entrypoint-initwp.d
    expose:
      - "9000"
    networks:
      - inception_network

  nginx:
    build:
      context: ./requirements/nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - wordpress-data:/var/www/html
      - ./requirements/nginx/wait-for-wordpress.sh:/wait-for-wordpress.sh
    entrypoint: ["/bin/sh", "-c", "/wait-for-wordpress.sh wordpress 9000 && nginx -g 'daemon off;'"]
    networks:
      - inception_network

# ======================
#    SECRETS & VOLUMES
# ======================

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt

volumes:
  mariadb-data:
  wordpress-data:

networks:
  inception_network:
    driver: bridge
