services:
  mariadb:
    build: ./requirements/mariadb
    restart: always
    secrets:
      - db_password
      - db_root_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - ./data/mariadb:/var/lib/mysql
    networks:
      - inception_network

  wordpress:
    build: ./requirements/wordpress
    restart: always
    depends_on:
      - mariadb
    secrets:
      - db_password
      - credentials
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
      DOMAIN_NAME: ${DOMAIN_NAME}
      CREDENTIALS_FILE: /run/secrets/credentials
    volumes:
      - ./data/wordpress:/var/www/html
      - ./requirements/wordpress/conf:/docker-entrypoint-initwp.d
    expose:
      - "9000"
    networks:
      - inception_network

  nginx:
    build:
      context: ./requirements/nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - ./data/wordpress:/var/www/html
      - ./requirements/nginx/conf/wait-for-wordpress.sh:/wait-for-wordpress.sh
      - ./requirements/nginx/conf/ssl:/etc/nginx/ssl
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    entrypoint: ["/bin/sh", "-c", "/wait-for-wordpress.sh wordpress 9000 && nginx -g 'daemon off;'"]
    networks:
      - inception_network

# ======================
#     SECRETS & NETWORK
# ======================

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt
  credentials:
    file: ./secrets/credentials.txt

networks:
  inception_network:
    driver: bridge
